[package]
name = "cea708-types"
description = "Closed Caption 708 types, parser and serializer"
version = "0.2.0"
authors = ["Matthew Waters <matthew@centricular.com>"]
license = "MIT"
edition = "2021"
keywords = ["multimedia", "captions"]
categories = ["multimedia::encoding"]
documentation = "https://docs.rs/cea708-types"
repository = "https://github.com/ystreet/cea708-types"

[dependencies]
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["std", "env-filter"] }
once_cell = "1"
muldiv = "1"
